version: '3.8'

services:
  database:
    image: mysql
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=world
    ports:
      - 3307:3306

  datapopulas_webserver:
    build: ./src
    restart: on-failure
    environment:
      - DATABASE_HOST=database
    command: npm start # Use npm start command to start the server
    ports:
      - 4000:4000
    depends_on:
      - database