version: 2.1
orbs:
  node : circleci/node@4.7.0
jobs:
  build :
    working_directory : ~/GROUP-COURSEWORK-SOFTWARE-ENGINEERING/src
    docker:
      - image : cimg/node:lts
    steps:
      - checkout:
          path: ~/GROUP-COURSEWORK-SOFTWARE-ENGINEERING 
      - run: npm install


      